# 底层数据服务配置
services:

    # STD 服务
    - name: STD
      # [必填]tcp udp
      protocol: tcp

      # [必填]监听的端口
      port: 9001

      # [必填]worker进程数
      child_count: 10

      # [选填]绑定的ip，注意：生产环境要绑定内网ip 不配置默认是0.0.0.0
      ip: 0.0.0.0

      # [选填]从客户端接收数据的超时时间, 默认为1000毫秒
      recv_timeout: 1000

      # [选填]业务逻辑处理超时时间
      process_timeout: 30000

      # [选填]发送数据到客户端超时时间
      send_timeout: 1000

      # [选填]是否是长连接, 不配置默认是短链接
      persistent_connection: true

      # [选填]进程接收多少请求后退出, 不配置默认是0，不退出
      max_requests: 1000

      # [必填]调用实体服务路径
      handle_path: ../apps/std

      # worker解析类
      worker_class: TextWorker

      # 数据签名用私匙
      rpc_secret_key: ab1f8e61026a7456289c550cb0cf77cda44302b4

    # 查询接口调用结果 只开一个进程 已经配置好，不用再配置
#    - name: StatisticGlobal
#      protocol: tcp
#      port: 9901
#      child_count: 1
#      ip: 0.0.0.0
#      recv_timeout: 1000
#      process_timeout: 1000
#      send_timeout: 1000
#      persistent_connection: true
#      max_requests: 1
#      handle_path: ../apps/StatisticGlobalHandle

    # 查询接口调用结果 只开一个进程 已经配置好，不用再配置
#    - name: StatisticProvider
#      protocol: tcp
#      port: 9902
#      child_count: 1
#      ip: 0.0.0.0
#      recv_timeout: 1000
#      process_timeout: 1000
#      send_timeout: 1000
#      persistent_connection: true
#      max_requests: 1
#      handle_path: ../apps/StatisticProviderHandle

# 开发环境: dev or production
env: dev

# 运行worker的用户,正式环境应该用低权限用户运行worker进程
worker_user: 


